CREATE DATABASE SGS;
USE SGS;

CREATE TABLE FUNCIONARIOS (
    idFUNCIONARIO INT PRIMARY KEY auto_increment,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(100) UNIQUE,
    CARGO ENUM('Médico', 'Secretário'),
    idMEDICO INT UNIQUE,
    idSECRETARIA INT UNIQUE
);

CREATE TABLE SECRETARIA (
    idSECRETARIA INT PRIMARY KEY auto_increment,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE MEDICO (
    idMEDICO INT PRIMARY KEY auto_increment,
    NOME VARCHAR(100),
    CRM VARCHAR(12) UNIQUE,
    ESPECIALIDADE VARCHAR(45),
    idFUNCIONARIO INT UNIQUE,
    FOREIGN KEY (idFUNCIONARIO) REFERENCES FUNCIONARIOS(idFUNCIONARIO)
);

CREATE TABLE PACIENTE (
    idPACIENTE INT PRIMARY KEY auto_increment,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(100) UNIQUE,
    ENDERECO VARCHAR(100)
);

CREATE TABLE PRONTUARIO (
    idPRONTUARIO INT PRIMARY KEY auto_increment,
    PRESCRICAO VARCHAR(200),
    OBSERVACOES VARCHAR(200),
    DIAGNOSTICO VARCHAR(100)
);

CREATE TABLE CONSULTA (
    idCONSULTA INT PRIMARY KEY auto_increment,
    DATA_HORA DATETIME,
    STATUS VARCHAR(45),
    idMEDICO INT,
    idPRONTUARIO INT,
    idSECRETARIA INT,
    idPACIENTE INT,
    FOREIGN KEY (idMEDICO) REFERENCES MEDICO(idMEDICO),
    FOREIGN KEY (idPRONTUARIO) REFERENCES PRONTUARIO(idPRONTUARIO),
    FOREIGN KEY (idSECRETARIA) REFERENCES SECRETARIA(idSECRETARIA),
    FOREIGN KEY (idPACIENTE) REFERENCES PACIENTE(idPACIENTE)
);

CREATE TABLE PACIENTEMEDICO (
    idMEDICO INT,
    idPACIENTE INT,
    PRIMARY KEY (idMEDICO, idPACIENTE),
    FOREIGN KEY (idMEDICO) REFERENCES MEDICO(idMEDICO),
    FOREIGN KEY (idPACIENTE) REFERENCES PACIENTE(idPACIENTE)
);
