create schema SGS;

use SGS;

CREATE TABLE CLINICA (
    idCLINICA INT auto_increment PRIMARY KEY,
    NOME VARCHAR(45),
    ENDERECO VARCHAR(45),
    TELEFONE INT,
    ESPECIALIDADES VARCHAR(45)
);

CREATE TABLE MEDICO (
    idMEDICO INT auto_increment PRIMARY KEY,
    NOME VARCHAR(45),
    CRM VARCHAR(12),
    ESPECIALIDADE VARCHAR(45),
    CLINICA_idCLINICA INT,
    FOREIGN KEY (CLINICA_idCLINICA) REFERENCES CLINICA(idCLINICA)
);

CREATE TABLE PACIENTE (
    idPACIENTE INT auto_increment PRIMARY KEY,
    NOME VARCHAR(45),
    CPF VARCHAR(11),
    DATANASCIMENTO DATE,
    TELEFONE INT,
    EMAIL VARCHAR(45)
);

CREATE TABLE CONSULTA (
    idCONSULTA INT auto_increment PRIMARY KEY,
    DATA_HORA VARCHAR(45),
    STATUS VARCHAR(45),
    MEDICO_idMEDICO INT,
    PACIENTE_idPACIENTE INT,
    FOREIGN KEY (MEDICO_idMEDICO) REFERENCES MEDICO(idMEDICO),
    FOREIGN KEY (PACIENTE_idPACIENTE) REFERENCES PACIENTE(idPACIENTE)
);

CREATE TABLE FICHA (
    idFICHA INT auto_increment PRIMARY KEY,
    DIAGNOSTICO VARCHAR(100),
    PRESCRICAO VARCHAR(100),
    OBSERVACOES VARCHAR(100),
    CONSULTA_idCONSULTA INT,
    FOREIGN KEY (CONSULTA_idCONSULTA) REFERENCES CONSULTA(idCONSULTA)
);

