CREATE DATABASE SGS;
USE SGS;

CREATE TABLE FUNCIONARIOS (
    idFUNCIONARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO VARCHAR(45),
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(100)
);

CREATE TABLE SECRETARIA (
    idSECRETARIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(100)
);

CREATE TABLE PACIENTE (
    idPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO VARCHAR(45),
    TELEFONE VARCHAR(45)
);

CREATE TABLE MEDICO (
    idMEDICO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45),
    CRM VARCHAR(12) UNIQUE,
    ESPECIALIDADE VARCHAR(45),
    FUNCIONARIOS_idFUNCIONARIOS INT,
    FOREIGN KEY (FUNCIONARIOS_idFUNCIONARIOS) REFERENCES FUNCIONARIOS(idFUNCIONARIOS)
);

CREATE TABLE PRONTUARIO (
    idPRONTUARIO INT PRIMARY KEY AUTO_INCREMENT,
    PRESCRICAO VARCHAR(200),
    OBSERVACOES VARCHAR(200),
    DIAGNOSTICO VARCHAR(100)
);

CREATE TABLE CONSULTA (
    idCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_HORA DATETIME,
    STATUS VARCHAR(45),
    MEDICO_idMEDICO INT,
    PRONTUARIO_idPRONTUARIO INT,
    SECRETARIA_idSECRETARIA INT,
    FOREIGN KEY (MEDICO_idMEDICO) REFERENCES MEDICO(idMEDICO),
    FOREIGN KEY (PRONTUARIO_idPRONTUARIO) REFERENCES PRONTUARIO(idPRONTUARIO),
    FOREIGN KEY (SECRETARIA_idSECRETARIA) REFERENCES SECRETARIA(idSECRETARIA)
);

CREATE TABLE PACIENTEMEDICO (
    MEDICO_idMEDICO INT,
    PACIENTE_idPACIENTE INT,
    PRIMARY KEY (MEDICO_idMEDICO, PACIENTE_idPACIENTE),
    FOREIGN KEY (MEDICO_idMEDICO) REFERENCES MEDICO(idMEDICO),
    FOREIGN KEY (PACIENTE_idPACIENTE) REFERENCES PACIENTE(idPACIENTE)
);


